# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 84344b37d603f579f07e2567c335e47166a14c92653ac5181be894d1882fc97fc2fe04a06cc4031c7374685d8af14297d4dbb533beffc461abc27bee2d92655b

test:
  secret_key_base: cf61ea14fc7e93b47a68326fc9dda0c9e0ca8ce197e230398efa6013557741d3180b54788d81ddf7571e2adb4635551960365d312ba8897feb017c468c027d7e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
